# spring.application.name=sportsceter

server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3366/sports-center
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: sportsceter
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect    
                format_sql: true

    data:
        redis:
            host: localhost
            port: 6379  